# Generated by Django 6.0.5 on 2026-09-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_db_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_act_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='rpt_st_pri_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityevent',
            name='secev_res_sev_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='tkt_st_pri_idx',
        ),
    ]
