# Generated by Django 6.0.5 on 2026-10-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_auditlog_audit_act_dt_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='platform_name',
            field=models.CharField(default='EventzUp', max_length=200),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='support_email',
            field=models.EmailField(default='support@eventzup.com', max_length=254),
        ),
    ]
