# Generated by Django 6.0.5 on 2026-05-22 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('venue', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('category', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('concert', 'Concert'), ('party', 'Party'), ('networking', 'Networking'), ('sports', 'Sports'), ('other', 'Other')], default='other', max_length=20)),
                ('max_capacity', models.PositiveIntegerField(default=100)),
                ('seat_arrangement', models.CharField(choices=[('general', 'General Admission'), ('reserved', 'Reserved Seating'), ('table', 'Table Seating'), ('vip', 'VIP Sections')], default='general', max_length=20)),
                ('vip_support', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
