# Generated by Django 6.0.5 on 2026-09-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_db_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='event_host_pub_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='event_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='event_susp_idx',
        ),
    ]
