# Generated by Django 6.0.5 on 2026-09-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_event_host_pub_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_subaccount_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
