# Generated by Django 6.0.5 on 2026-09-22 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_host_subaccount_code_event_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['host', '-date'], name='event_host_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='event_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='event_category_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_suspended', 'is_archived'], name='event_admin_flags_idx'),
        ),
    ]
