# Generated by Django 6.0.5 on 2026-09-24 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_options_event_event_host_date_idx_and_more'),
        ('guest', '0004_guest_amount_paid_guest_payment_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Human-readable seat identifier, e.g. 'A-1', 'Table 3 Chair B'", max_length=50)),
                ('section', models.CharField(blank=True, default='', help_text="Optional grouping, e.g. 'Family', 'VIP', 'Front row'", max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('taken', 'Taken'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('held_for', models.CharField(blank=True, default='', help_text="When status is 'held', who the seat is reserved for.", max_length=200)),
                ('held_note', models.TextField(blank=True, default='', help_text='Optional note about the hold.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order; lower numbers come first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='event.event')),
                ('guest', models.OneToOneField(blank=True, help_text='Set when a guest is assigned to this seat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_seat', to='guest.guest')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ['sort_order', 'label'],
                'indexes': [models.Index(fields=['event', 'status'], name='seat_event_status_idx'), models.Index(fields=['event', 'section'], name='seat_event_section_idx'), models.Index(fields=['event', 'sort_order'], name='seat_event_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'label'), name='unique_seat_label_per_event')],
            },
        ),
    ]
