# Generated by Django 6.0.5 on 2026-09-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='access_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional. Guests who enter this code during registration get seated in this group automatically.', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='seat_arrangement',
            field=models.CharField(choices=[('general', 'General Admission'), ('reserved', 'Reserved Seating')], default='general', max_length=20),
        ),
    ]
