# Generated by Django 6.0.5 on 2026-10-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_seat_access_code_alter_event_seat_arrangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_listed',
            field=models.BooleanField(default=False, help_text='Show this event in the public marketplace browse page and homepage.'),
        ),
    ]
