# Generated by Django 6.0.5 on 2026-10-09 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_event_is_listed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published', 'is_listed', 'date'], name='event_public_idx'),
        ),
    ]
