# Generated by Django 6.0.5 on 2026-09-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_db_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendor_act_susp_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendor_verif_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendor_city_idx',
        ),
    ]
