# Generated by Django 6.0.5 on 2026-09-18 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_remove_vendor_vendor_act_susp_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('portfolio_limit', models.PositiveIntegerField(default=8)),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_featured_placement', models.BooleanField(default=False)),
                ('has_video_portfolio', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('paystack_plan_code', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('free', 'Free')], default='free', max_length=20)),
                ('trial_start_at', models.DateTimeField(blank=True, null=True)),
                ('trial_end_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('paystack_subscription_code', models.CharField(blank=True, default='', max_length=100)),
                ('paystack_email_token', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.subscriptionplan')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='vendors.vendor')),
            ],
        ),
    ]
