# Generated by Django 6.0.5 on 2026-05-22 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('meal_preference', models.CharField(blank=True, default='', max_length=100)),
                ('plus_one', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('seat_number', models.CharField(blank=True, default='', max_length=50)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('ticket_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='event.event')),
            ],
            options={
                'ordering': ['seat_number'],
            },
        ),
    ]
