# Generated by Django 6.0.5 on 2026-09-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_db_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='guest',
            name='guest_event_chk_idx',
        ),
        migrations.RemoveIndex(
            model_name='guest',
            name='guest_ticket_idx',
        ),
    ]
