# Generated by Django 6.0.5 on 2026-09-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_remove_guest_guest_event_chk_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
