# Generated by Django 6.0.5 on 2026-05-27 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField()),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('includes', models.TextField(blank=True, default='')),
                ('terms', models.TextField(blank=True, default='')),
                ('estimated_duration_hours', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['proposed_price'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('budget_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('required_date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('special_requirements', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Proposals'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('agreed_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_notes', models.TextField(blank=True, default='')),
                ('host_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='event.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
