# Generated by Django 6.0.5 on 2026-09-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_db_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_ven_st_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_evt_st_idx',
        ),
        migrations.RemoveIndex(
            model_name='proposal',
            name='prop_ven_st_idx',
        ),
        migrations.RemoveIndex(
            model_name='quoterequest',
            name='rfq_st_urg_idx',
        ),
    ]
